name: CI

on: [delete]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: print-ref
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Ref: $GITHUB_REF
        echo SHA: $GITHUB_SHA
        echo ${{ github }}
